[package]
name = "taffy-issue"
edition = "2021"
version = "0.1.0"

[dependencies.taffy]
version = "0.4.0"
features = ["grid", "block_layout", "std", "content_size", "taffy_tree"]
default-features = false
